<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.navistack.boot</groupId>
        <artifactId>navi-boot</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>navi-boot-web</artifactId>

    <dependencies>
        <!-- Navi Boot -->
        <dependency>
            <groupId>org.navistack.boot</groupId>
            <artifactId>navi-boot-core</artifactId>
        </dependency>

        <!-- Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-webmvc</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-security</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Navi Framework -->
        <dependency>
            <groupId>org.navistack.framework</groupId>
            <artifactId>navi-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.navistack.framework</groupId>
            <artifactId>navi-captcha</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.navistack.framework</groupId>
            <artifactId>navi-ratelimit</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.navistack.framework</groupId>
            <artifactId>navi-locking</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.navistack.framework</groupId>
            <artifactId>navi-security</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Jackson -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>
</project>
